Also set -mavx512bw when compiling blake3_avx512 to fix compilation on CentOS 8
GCC 8.3.1 20191121 (Red Hat 8.3.1-5) was erroring out with:

	Error: unsupported instruction `vmovdqu'

https://github.com/BLAKE3-team/BLAKE3/issues/58 advised this was previously caused by a compiler bug up to 6.3, but that clearly isn't applicable here. But, the fix/workaround posted in comment https://github.com/BLAKE3-team/BLAKE3/issues/58#issuecomment-584615232 works.